spring.application.name=maphub
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

server.servlet.session.timeout=30m
spring.sql.init.mode=always

# Uses Pterodactyl's assigned port, defaults to 8081 if not found
server.port=${SERVER_PORT}

# Binds to all network interfaces so it can be accessed externally
server.address=0.0.0.0

api.proxy.base-url=${PROXY_API_URL}